select  A.FILIAL, A.NF_ENTRADA, A.SERIE_NF_ENTRADA, B.CODIGO_ITEM, B.CLASSIF_FISCAL, B.ORIGEM_ITEM, B.*
	from ENTRADAS A
	inner join ENTRADAS_ITEM B
		on A.NOME_CLIFOR=B.NOME_CLIFOR
		and A.NF_ENTRADA=B.NF_ENTRADA
		and A.SERIE_NF_ENTRADA=B.SERIE_NF_ENTRADA
	inner join FILIAIS F
		on A.FILIAL=F.FILIAL
where A.RECEBIMENTO between '20210401' and '20210430'
--a.NF_ENTRADA='050421'
and F.FILIAL IN ('pier 21')
AND B.DESCRICAO_ITEM like '%IPT%'


		UPDATE ENTRADAS_ITEM
		SET CODIGO_ITEM='S-000070' 
		from ENTRADAS A
	inner join ENTRADAS_ITEM B
		on A.NOME_CLIFOR=B.NOME_CLIFOR
		and A.NF_ENTRADA=B.NF_ENTRADA
		and A.SERIE_NF_ENTRADA=B.SERIE_NF_ENTRADA
	inner join FILIAIS F
		on A.FILIAL=F.FILIAL
	where A.RECEBIMENTO between '20210401' and '20210430'
		and F.FILIAL IN ('pier 21')
AND B.DESCRICAO_ITEM='AR CONDICIONADO - ALUGUEL'
and a.NF_ENTRADA='050421'
		


IPTU - ALUGUEL - S-000073
AR CONDICIONADO - ALUGUEL- S-000070            
ALUGUEL - PJ - S-000063
CONDOMÍNIO - S-000152 