SELECT P.PRODUTO, P.DESC_PRODUTO, CAT.PRECO1 AS PRECO_ATACADO,COU.PRECO1 AS PRECO_VENDA_OUTLET,
CPC.PRECO1 AS PRECO_CUSTO,CPT.PRECO1 AS PRECO_TRANSFERENCIA, CVC.PRECO1 AS PRECO_VENDA_RETAGUARDA, CVE.PRECO1 AS PRECO_VENDA_ECOM,
CVO.PRECO1 AS PRECO_VENDA_ORIGINAL,CVV.PRECO1 AS PRECO_VENDA_VAREJO,CZZ.PRECO1 AS PRECO_VENDAS_ZZ FROM PRODUTOS P
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'AT') CAT 
	ON P.PRODUTO = CAT.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'OU') COU 
	ON P.PRODUTO = COU.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'PC') CPC
	ON P.PRODUTO = CPC.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'PT') CPT 
	ON P.PRODUTO = CPT.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'VC') CVC 
	ON P.PRODUTO = CVC.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'VE') CVE 
	ON P.PRODUTO = CVE.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'VO') CVO 
	ON P.PRODUTO = CVO.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'VV') CVV 
	ON P.PRODUTO = CVV.PRODUTO
	LEFT JOIN(
SELECT PRODUTO, PRECO1 FROM PRODUTOS_PRECOS
WHERE  CODIGO_TAB_PRECO = 'ZZ') CZZ
	ON P.PRODUTO = CZZ.PRODUTO
ORDER BY P.PRODUTO
