alter VIEW [dbo].[W_INFORMACAO_PAGAMENTO] 
-- DANIEL JUNIOR(SS) e RAI MIGUEL(SS)- #SS01# - 16/07/2020 - AJUSTE NO JOIN COM TABELA UNICO_VITRINE_PEDIDO PARA LIGAR TODAS OS CAMPOS CHAVES DO LOJA_VENDA_PARCELAS   
-- SUSTSP-475- ANDRÉ ARTUZO		   - #24# - 11/06/2020 - Ajuste pois gerou efeito colateral na correção #23# 	
-- POSSP-3251- ANDRÉ ARTUZO		   - #23# - 08/06/2020 - Correção para não gerar valor do Frete no pagamento em Ship sem Frete. 	
-- MD 8409   - EDER SILVA		   - #22# - 18/11/2019 - Correção emissão de nota com Vitrine - com e sem 'venda a ordem'.
-- MD 2853   - DIEGO MORENO		   - #21# - 07/06/2019 - Melhoria do tratamento anterior devido a ter gerado efeito colateral.
-- MD 2595   - Wendel Crespigio    - #20# - 05/06/2019 - Inclusão de codigo para emissão de Venda à Ordem.
-- MD 1800   - Wesley Batista      - #19# - 22/05/2019 - Ajuste para evitar lançar troco incorreto em uma nota de venda onde existe uma troca e o produto trocado e com valor acima do que estão sendo levados pelo cliente. - Efetuada uma alteração retirando impacto de outras modificações na view - acordado entre Wendel/Diego/Edson/Wesley
-- DM 113415 - Gilvano Santos      - #18# - 23/03/2019 - Reconhecer a forma de pagamento Vale Troca como Credito Loja
-- DM 109532 - Eder Silva          - #17# - 14/02/2019  - NF-e 4.0 - Removido o meio de pagamento 14 (Duplicata Mercantil) conforme NT 2016.002 Versão 1.61 e alinhado com Roberto Beda.
-- DM 98241  - Eder Silva          - #16# - 23/10/2018  - NF-e 4.0 - Correção no vinculo entre notas de venda e notas vinculadas (natureza 5929). 
-- DM 76917  - Wendel Crespigio    - #15# - 28/05/2018  - NF-e 4.0 - Tratamento para melhoria de performace 
-- DM 73654  - Fabio Santos/Artuzo - #14# - 09/05/2018  - NF-e 4.0 - Ajuste para incluir a série da nota nos joins.  
-- DM 72869  - Eder Silva          - #13# - 02/05/2018  - NF-e 4.0 - Correção para informar o código correto da BANDEIRA.  
-- DM 70256  - Wendel Crespigio    - #12# - 12/04/2018  - NF-e 4.0 - CORREÇÃO PARA TROCA MAIOR QUE A VENDA valor troco  
-- DM 70256  - Wendel Crespigio    - #11# - 12/04/2018  - NF-e 4.0 - CORREÇÃO PARA TROCA MAIOR QUE A VENDA valor troco  
-- DM 70256  - Wendel Crespigio    - #10# - 12/04/2018  - NF-e 4.0 - Verificando valores negatios para mais tipos de pagamentos   
-- DM 70547  - Wendel Crespigio    - #9# - (11/04/2018) - NF-e 4.0 - Nota fiscal com troca     
-- DM 68765  - Wendel Crespigio    - #8# - (28/03/2018  - NF-e 4.0 - Nota com arredontar o arredondar tem que entrar como troco conforme verificação SEFAZ  
-- DM 67298  - Wendel Crespigio    - #7# - (14/03/2018) - NF-e 4.0 - NFCe - Acima de 20 mil retorno de NFe (Valor do troco incorreto)  
-- DM 66767  - Wendel Crespigio    - #6# - (13/03/2018) - NF-e 4.0 - Tratamento para quando o parametro Utilizar ticket como número de cupom estiver habilidato   
-- DM 62953  - Diego Moreno        - #5# - (20/02/2018) - NF-e 4.0 - Melhoria para considerar vendas com o parâmetro "Utilizar ticket como número de cupom" onde a coluna NUMERO_CUPOM_FISCAL fica preenchida para uma NF-e de uma NFC-e.  
-- DM 61973  - Wendel Crespigio    - #4# - (09/02/2018) - NF-e 4.0 - Correção para nota fiscal de transferencia.    
-- DM 62619  - Diego Moreno        - #3# - (09/02/2018) - NF-e 4.0 - Correção na validação de notas vinculadas para NFC-e e Sat para geração das tags de pagamento.  
-- DM 61554  - Diego Moreno        - #2# - (06/02/2018) - NF-e 4.0 - Melhoria para que cada tipo de nota seja identificado no filtro da view.  
-- DM 58430  - Diego Moreno        - #1# - (02/01/2018) - NF-e 4.0 - Criação da view para isolar a identificação das informações das parcelas de venda para NF-e.      
AS      
/********************************************* NOTA FISCAL DE VENDA VINCULADA*****************************************************/    
SELECT   
 'V1' AS TIPO_NOTA,  /*#4#*/  
 LOJA.FILIAL,PGTO.NUMERO_FISCAL_VINCULADA AS NF, PGTO.SERIE_NF_VINCULADA AS SERIE_NF, PARCELA.PARCELA,      
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('D','M')		THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('C','P')     THEN '02'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I') THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('E','K')     THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('#','@','N','>') THEN '05'      --#18#
	WHEN PARCELA.TIPO_PGTO = '&'			THEN '12'      
  --WHEN PARCELA.TIPO_PGTO = 'J'			THEN '14'      -- #17#
	WHEN PARCELA.TIPO_PGTO = 'T'			THEN '90'      
	ELSE '99'       
 END) AS INFO_PGTO,  
 CASE WHEN PARCELA.VALOR > 0 THEN PARCELA.VALOR ELSE 0 END AS VALOR,  --#8#     
 (D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA,      
 (CASE WHEN PARCELA.TIPO_PGTO IN ('K','I')  THEN 1       
   WHEN PARCELA.TIPO_PGTO IN ('E','B','A')  THEN 2       
   ELSE NULL   
 END) AS TIPO_INTEGRA,       
  -- #13# - Início  
  -- Passou a validar o nome da Administradora da tabela 'LX_ADMINISTRADORAS_CARTAO'  
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
	ELSE NULL   
 END) BANDEIRA,      
  -- #13# - Fim    
    (CASE WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO ELSE NULL END) AS AUTORIZACAO,      
    ISNULL((PARCELA.TROCO ),0) +   
  CASE WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
    WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0                 THEN ABS(PARCELA.VALOR) -- AND PARCELA.VALOR = > 0 AND PARCELA.TROCO = 0  
    ELSE 0   
  END AS TROCO  --#8# #10# #11#    
FROM LOJA_VENDA_PGTO PGTO  with (nolock)  --#15#  
  INNER JOIN LOJA_VENDA_PARCELAS PARCELA   with (nolock)   --#15#
     ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL  AND     
                       PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
                       PGTO.TERMINAL = PARCELA.TERMINAL      
  INNER JOIN LOJAS_VAREJO LOJA  with (nolock) --#15#      
                    ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
  LEFT JOIN ADMINISTRADORAS_CARTAO C  with (nolock) --#15#   
                    ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
  LEFT JOIN CREDENCIADORA_CARTAO D with (nolock)  --#15#
                    ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA      
  INNER JOIN LOJA_NOTA_FISCAL NOTA   with (nolock) --#15#
                    ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
                       NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VINCULADA AND  
                       NOTA.SERIE_NF = PGTO.SERIE_NF_VINCULADA  
  LEFT JOIN LX_ADMINISTRADORAS_CARTAO E  with (nolock) -- #13#  #15#
     ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #13#  
          /*#2#*/  
WHERE ((PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL AND  
          PGTO.NUMERO_FISCAL_VENDA IS  NULL AND --#3#  
          PGTO.NUMERO_FISCAL_VINCULADA IS NOT NULL AND  
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '')  
          OR  
          /*#2#*/  
          (PGTO.NUMERO_CUPOM_FISCAL IS NULL AND  
          PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
          PGTO.NUMERO_FISCAL_VINCULADA IS NOT NULL AND   
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '')  
          OR  
          (PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL AND --#5#  
          PGTO.NUMERO_FISCAL_VENDA IS  NOT NULL AND --#3#  
          PGTO.NUMERO_FISCAL_VINCULADA IS NOT NULL AND --#5#  
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '') --#5#  
          )  
          
/********************************************* NOTA FISCAL DE VENDA VINCULADA*****************************************************/    
UNION  ALL 
  
SELECT   
 'V2' as TIPO_NOTA,  /*#4#*/  
 LOJA.FILIAL,PGTO.NUMERO_FISCAL_VENDA AS NF, PGTO.SERIE_NF_SAIDA AS SERIE_NF, PARCELA.PARCELA, -- #15#     
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('D','M')		THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('C','P')		THEN '02'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I') THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('E','K')		THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('#','@','N','>') THEN '05'      --#18#
	WHEN PARCELA.TIPO_PGTO = '&'			THEN '12'      
  --WHEN PARCELA.TIPO_PGTO = 'J'			THEN '14'  -- #17#    
	WHEN PARCELA.TIPO_PGTO = 'T'			THEN '90'      
	ELSE '99'       
 END) AS INFO_PGTO,       
 CASE WHEN PARCELA.VALOR > 0 THEN PARCELA.VALOR ELSE 0 END AS VALOR, --#8#          
 (D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA,      
 (CASE WHEN PARCELA.TIPO_PGTO IN ('K','I')  THEN 1       
   WHEN PARCELA.TIPO_PGTO IN ('E','B','A') THEN 2       
   ELSE NULL   
 END) AS TIPO_INTEGRA,  
  -- #13# - Início  
  -- Passou a validar o nome da Administradora da tabela 'LX_ADMINISTRADORAS_CARTAO'  
 (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
	ELSE NULL   
   END) BANDEIRA,      
  -- #13# - Fim  
 (CASE WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO ELSE NULL END) AS AUTORIZACAO,      
 ISNULL((PARCELA.TROCO ),0) +   
  CASE WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
    WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0     THEN ABS(PARCELA.VALOR) -- AND PARCELA.VALOR = > 0 AND PARCELA.TROCO = 0  
    ELSE 0   
  END AS TROCO --#8#  #10# #11#    
FROM LOJA_VENDA_PGTO PGTO   with (nolock)  --#15# 
  INNER JOIN LOJA_VENDA_PARCELAS PARCELA  with (nolock)  --#15#
     ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL  AND     
     PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
     PGTO.TERMINAL = PARCELA.TERMINAL      
  INNER JOIN LOJAS_VAREJO LOJA with (nolock)     --#15#
     ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
  LEFT JOIN ADMINISTRADORAS_CARTAO C  with (nolock) --#15#
     ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
  LEFT JOIN CREDENCIADORA_CARTAO D   with (nolock) --#15#
     ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA       
  INNER JOIN LOJA_NOTA_FISCAL NOTA  with (nolock)  --#15#
                    ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
     NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VENDA AND  
     NOTA.SERIE_NF = PGTO.SERIE_NF_SAIDA  
  LEFT JOIN LX_ADMINISTRADORAS_CARTAO E  with (nolock)-- #13#  
     ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  -- #13#  
    /*#2#*/ 
/*#SS01# - In�cio*/
	--LEFT JOIN (Select A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
	LEFT JOIN (Select A.TERMINAL,A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
	   DESCONTO_LOJA,CANCELADO,FRETE From UNICO_VITRINE_PEDIDO UV  with (nolock)
       INNER JOIN LOJA_VENDA A with (nolock)
	on A.TICKET = UV.TICKET 
	   And A.DATA_VENDA = UV.DATA_VENDA 
	   And A.CODIGO_FILIAL =UV.CODIGO_FILIAL ) VV --#20#
	on PARCELA.LANCAMENTO_CAIXA = VV.LANCAMENTO_CAIXA  
	   --and PARCELA.CODIGO_FILIAL =  VV.CODIGO_FILIAL
	   and PARCELA.CODIGO_FILIAL =  VV.CODIGO_FILIAL and PARCELA.TERMINAL = VV.TERMINAL
/*#SS01# - Fim*/
WHERE ((PGTO.ID_EQUIPAMENTO IS NOT NULL AND  
    PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND  
          PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL )  
          OR  
          (PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
          ISNULL(PGTO.ID_EQUIPAMENTO , '') = '' AND   
          --PGTO.NUMERO_CUPOM_FISCAL IS NULL AND  #6#  
          PGTO.NUMERO_FISCAL_VINCULADA IS NULL))
		  AND isnull(VV.VALOR_ORIGINAL_PEDIDO,0) = 0  --#20# #21#
		  AND ISNULL(PARCELA.CHEQUE_DIGITO,'') <> 'N' --#23# #24#
    /*#2#*/  
UNION ALL  
     
SELECT     
 'O'			AS TIPO_NOTA,  /*#4#*/   
 B.FILIAL,       
 A.NF_NUMERO	AS NF,       
 A.SERIE_NF, 1	AS PARCELA,      
 '90'			AS INFO_PGTO,      
 A.VALOR_TOTAL	AS VALOR,      
 ''				AS CNPJ_CREDENCIADORA,      
 '2'			AS TIPO_INTEGRA,       
 '99'			AS BANDEIRA,      
 ''				AS AUTORIZACAO,      
 0				AS TROCO        
FROM LOJA_NOTA_FISCAL A with (nolock)     --#15#
  INNER JOIN LOJAS_VAREJO B with (nolock)     --#15#
     ON A.CODIGO_FILIAL = B.CODIGO_FILIAL      
  LEFT JOIN LOJA_VENDA_PGTO  C  with (nolock)   --#15# 
     ON A.CODIGO_FILIAL = C.CODIGO_FILIAL AND    
     -- #16# - Início
	 --(A.NF_NUMERO = C.NUMERO_FISCAL_VENDA OR A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA ) AND  
     --(A.SERIE_NF = C.SERIE_NF_VINCULADA OR A.SERIE_NF = C.SERIE_NF_SAIDA) --#14#  
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VENDA     and A.SERIE_NF = C.SERIE_NF_SAIDA) or   
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA and A.SERIE_NF = C.SERIE_NF_VINCULADA)  
     -- #16# - Fim
WHERE C.NUMERO_FISCAL_VINCULADA IS NULL AND    
  C.NUMERO_FISCAL_VENDA     IS NULL AND  --#7#    
  --C.NUMERO_FISCAL_VINCULADA IS NULL   AND #7#  
  A.TIPO_ORIGEM <> 1 /*#2#*/  
  
UNION ALL -- TRATAMENTO PARA FAZER O VALOR DA TROCA COM DINHEIRO COM TIPO OUTROS #9#  
  
SELECT     
 'V3'			AS TIPO_NOTA,  /*#4#*/   
 B.FILIAL,       
 A.NF_NUMERO	AS NF,       
 A.SERIE_NF,  
 PARCELA.PARCELA +1 AS PARCELA,  
 '99'			AS INFO_PGTO,      
 CASE WHEN D.VALOR_TIKET < 0 THEN D.VALOR_VENDA_BRUTA  ELSE D.VALOR_TROCA END AS VALOR,  --#19# 
 --D.VALOR_VENDA_BRUTA  AS VALOR ,      
 NULL			AS CNPJ_CREDENCIADORA,      
 NULL			AS TIPO_INTEGRA,       
 NULL			AS BANDEIRA,      
 NULL			AS AUTORIZACAO,      
 0				AS TROCO        
FROM LOJA_NOTA_FISCAL A  with (nolock)   --#15# 
  INNER JOIN LOJAS_VAREJO B  with (nolock) --#15#     
     ON A.CODIGO_FILIAL = B.CODIGO_FILIAL      
  LEFT JOIN LOJA_VENDA_PGTO  C with (nolock)   --#15#  
     ON A.CODIGO_FILIAL = C.CODIGO_FILIAL AND
     -- #16# - Início	     
	 --(A.NF_NUMERO = C.NUMERO_FISCAL_VENDA OR A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA ) AND  
     --(A.SERIE_NF = C.SERIE_NF_VINCULADA OR A.SERIE_NF = C.SERIE_NF_SAIDA) --#14#  
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VENDA     and A.SERIE_NF = C.SERIE_NF_SAIDA) or   
	 (A.NF_NUMERO = C.NUMERO_FISCAL_VINCULADA and A.SERIE_NF = C.SERIE_NF_VINCULADA)  
     -- #16# - Fim
  INNER JOIN LOJA_VENDA D   with (nolock) --#15#
     ON A.CODIGO_FILIAL = D.CODIGO_FILIAL AND   
     C.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA AND   
     C.TERMINAL = D.TERMINAL  
  INNER JOIN (SELECT MAX(PARCELA) AS PARCELA ,CODIGO_FILIAL,LANCAMENTO_CAIXA,TERMINAL   
      FROM LOJA_VENDA_PARCELAS with (nolock) /*#12#  #15#  */ GROUP BY CODIGO_FILIAL,TERMINAL,LANCAMENTO_CAIXA ) AS PARCELA  
     ON D.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL   AND     
     D.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
     D.TERMINAL = PARCELA.TERMINAL
 /*#SS01# - In�cio*/
  --LEFT JOIN (Select A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
  LEFT JOIN (Select A.TERMINAL,A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,CONFIRMADO,CANCELADO
		DESCONTO_LOJA,CANCELADO,FRETE 
	FROM UNICO_VITRINE_PEDIDO UV WITH (NOLOCK)
  INNER JOIN LOJA_VENDA A WITH (NOLOCK)
	on A.TICKET = UV.TICKET 
	  And A.DATA_VENDA = UV.DATA_VENDA 
	  And A.CODIGO_FILIAL =UV.CODIGO_FILIAL
	  And A.DATA_VENDA BETWEEN CONVERT(CHAR(8),GETDATE()-30,112) AND CONVERT(CHAR(8),GETDATE(),112)) VV --#20#
	on PARCELA.LANCAMENTO_CAIXA =VV.LANCAMENTO_CAIXA 
	  And PARCELA.CODIGO_FILIAL=VV.CODIGO_FILIAL 
	  --And D.DATA_VENDA = VV.DATA_VENDA    
	  And D.DATA_VENDA = VV.DATA_VENDA and D.TERMINAL = VV.TERMINAL
/*#SS01# - Fim*/ 
	WHERE D.VALOR_TROCA > 0 
	   AND isnull(VV.VALOR_ORIGINAL_PEDIDO,0) = 0 --#20# #21#

/************************************************ NOTA FISCAL DE VENDA À ORDEM VITRINE ********************************************************************************/

UNION ALL --#20#
   
 SELECT A.TIPO_NOTA,FILIAL, NF ,SERIE_NF,PARCELA,INFO_PGTO,VALOR, MAX(CNPJ_CREDENCIADORA),MAX(TIPO_INTEGRA) ,MAX(BANDEIRA),MAX(AUTORIZACAO), MAX(TROCO)
 From (
 SELECT 'V4' as TIPO_NOTA, 
 LOJA.FILIAL,PGTO.NUMERO_FISCAL_VENDA AS NF, PGTO.SERIE_NF_SAIDA AS SERIE_NF, '01' as Parcela , 
 '99' AS INFO_PGTO,       
 (VALOR_ORIGINAL_PEDIDO - isnull(NOTA.DESCONTO,0)) VALOR, 
 (D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA,      
 (CASE WHEN PARCELA.TIPO_PGTO IN ('K','I')  THEN 1       
   WHEN PARCELA.TIPO_PGTO IN ('E','B','A')  THEN 2       
   ELSE NULL   
 END) AS TIPO_INTEGRA,  
  (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
	ELSE NULL   
   END) BANDEIRA,      
   (CASE WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO ELSE NULL END) AS AUTORIZACAO,      
 ISNULL((PARCELA.TROCO ),0) +   
  CASE WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
    WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0     THEN ABS(PARCELA.VALOR) 
    ELSE 0   
  END AS TROCO 
FROM LOJA_VENDA_PGTO PGTO   with (nolock)  
  INNER JOIN LOJA_VENDA_PARCELAS PARCELA  with (nolock)  
     ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL  AND     
     PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
     PGTO.TERMINAL = PARCELA.TERMINAL      
  INNER JOIN LOJAS_VAREJO LOJA with (nolock)     
     ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
  LEFT JOIN ADMINISTRADORAS_CARTAO C  with (nolock) 
     ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
  LEFT JOIN CREDENCIADORA_CARTAO D   with (nolock) 
     ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA       
  INNER JOIN LOJA_NOTA_FISCAL NOTA  with (nolock)  
    ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
     NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VENDA AND  
     NOTA.SERIE_NF = PGTO.SERIE_NF_SAIDA AND
	 NOTA.NATUREZA_OPERACAO_CODIGO IN ('5120','5.120','6120','6.120')  --#22# somente notas venda à ordem
  LEFT JOIN LX_ADMINISTRADORAS_CARTAO E  with (nolock)
     ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  
	/*#SS01# - In�cio*/
	--LEFT JOIN (Select A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,(VALOR_ORIGINAL_PEDIDO - isnull(DESCONTO_LOJA,0)) VALOR_TOTAL ,CONFIRMADO,CANCELADO
	LEFT JOIN (Select A.TERMINAL,A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,(VALOR_ORIGINAL_PEDIDO - isnull(DESCONTO_LOJA,0)) VALOR_TOTAL ,CONFIRMADO,CANCELADO
	DESCONTO_LOJA,CANCELADO,FRETE from UNICO_VITRINE_PEDIDO UV WITH (NOLOCK)
         INNER JOIN LOJA_VENDA A WITH (NOLOCK)
	 ON  A.TICKET = UV.TICKET 
	And A.DATA_VENDA = UV.DATA_VENDA 
	And A.CODIGO_FILIAL =UV.CODIGO_FILIAL
	And A.DATA_VENDA BETWEEN CONVERT(CHAR(8),GETDATE()-30,112) AND CONVERT(CHAR(8),GETDATE(),112)) VV
	--on PARCELA.LANCAMENTO_CAIXA =VV.LANCAMENTO_CAIXA 
	on PARCELA.CODIGO_FILIAL = VV.CODIGO_FILIAL AND PARCELA.TERMINAL = VV.TERMINAL AND PARCELA.LANCAMENTO_CAIXA =VV.LANCAMENTO_CAIXA 
/*#SS01# - Fim*/ 
	WHERE ((PGTO.ID_EQUIPAMENTO IS NOT NULL AND  
		PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND  
			  PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL )  
			OR  
			(PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
			ISNULL(PGTO.ID_EQUIPAMENTO , '') = '' AND   
			PGTO.NUMERO_FISCAL_VINCULADA IS NULL))
			AND isnull(VV.VALOR_ORIGINAL_PEDIDO,0) > 0  --#20#
			) A 
		  GROUP BY A.TIPO_NOTA,FILIAL, NF ,SERIE_NF,PARCELA,INFO_PGTO,VALOR --#20# #21#

/************************************************ NOTA FISCAL SEM VENDA ORDEM (5120,6120)  ********************************************************************************/
UNION ALL 
   
 SELECT A.TIPO_NOTA,FILIAL, NF, SERIE_NF, PARCELA,INFO_PGTO,VALOR, MAX(CNPJ_CREDENCIADORA),MAX(TIPO_INTEGRA) ,MAX(BANDEIRA),MAX(AUTORIZACAO), MAX(TROCO)
 From (
 SELECT 'V5' as TIPO_NOTA,  --#22#
 LOJA.FILIAL,PGTO.NUMERO_FISCAL_VENDA AS NF, PGTO.SERIE_NF_SAIDA AS SERIE_NF, '01' as Parcela , 
 '99' AS INFO_PGTO,       
 --(VALOR_ORIGINAL_PEDIDO - isnull(NOTA.DESCONTO,0)) VALOR, --#22#
 VV.VALOR_PAGO AS VALOR,  --#22#
 (D.CNPJ_CREDENCIADORA) AS CNPJ_CREDENCIADORA,      
 (CASE WHEN PARCELA.TIPO_PGTO IN ('K','I')  THEN 1       
   WHEN PARCELA.TIPO_PGTO IN ('E','B','A')  THEN 2       
   ELSE NULL   
 END) AS TIPO_INTEGRA,  
  (CASE 
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%VISA%'				THEN '01'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%MASTERCARD%'			THEN '02'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AMERICAN EXPRESS%'	THEN '03'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%SOROCRED%'			THEN '04'      
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%DINERS%'				THEN '05'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%ELO%'				THEN '06'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%HIPERCARD%'			THEN '07'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%AURA%'				THEN '08'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') AND E.LX_ADMINISTRADORA LIKE '%CABAL%'				THEN '09'       
	WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K')														THEN '99'       
	ELSE NULL   
   END) BANDEIRA,      
   (CASE WHEN PARCELA.TIPO_PGTO IN ('A','B','I','E','K') THEN PARCELA.NUMERO_APROVACAO_CARTAO ELSE NULL END) AS AUTORIZACAO,      
 ISNULL((PARCELA.TROCO ),0) +   
  CASE 
	WHEN PARCELA.TIPO_PGTO IN ('^','&','@','R','V','>') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR)     --#18#
    WHEN PARCELA.TIPO_PGTO IN ('D') AND PARCELA.VALOR < 0 AND PARCELA.TROCO = 0 THEN ABS(PARCELA.VALOR) 
    WHEN VV.VALOR_TOTAL > 0 AND VV.VALOR_PAGO > 0 THEN VV.VALOR_TOTAL - VV.VALOR_PAGO  --#22#
	ELSE 0   
  END AS TROCO 
FROM LOJA_VENDA_PGTO PGTO   with (nolock)  
  INNER JOIN LOJA_VENDA_PARCELAS PARCELA  with (nolock)  
     ON PGTO.CODIGO_FILIAL = PARCELA.CODIGO_FILIAL  AND     
     PGTO.LANCAMENTO_CAIXA = PARCELA.LANCAMENTO_CAIXA AND   
     PGTO.TERMINAL = PARCELA.TERMINAL      
  INNER JOIN LOJAS_VAREJO LOJA with (nolock)     
     ON PARCELA.CODIGO_FILIAL = LOJA.CODIGO_FILIAL      
  LEFT JOIN ADMINISTRADORAS_CARTAO C  with (nolock) 
     ON C.CODIGO_ADMINISTRADORA = PARCELA.CODIGO_ADMINISTRADORA      
  LEFT JOIN CREDENCIADORA_CARTAO D   with (nolock) 
     ON D.COD_CREDENCIADORA = PARCELA.COD_CREDENCIADORA       
  INNER JOIN LOJA_NOTA_FISCAL NOTA  with (nolock)  
	 ON NOTA.CODIGO_FILIAL = PGTO.CODIGO_FILIAL AND  
     NOTA.NF_NUMERO = PGTO.NUMERO_FISCAL_VENDA AND  
     NOTA.SERIE_NF = PGTO.SERIE_NF_SAIDA  AND
	 NOTA.NATUREZA_OPERACAO_CODIGO NOT IN ('5120','5.120','6120','6.120')  --#22# não selecionar notas de venda à ordem
  LEFT JOIN LX_ADMINISTRADORAS_CARTAO E  with (nolock)
     ON LTRIM(RTRIM(C.LX_COD_ADMINISTRADORA)) = LTRIM(RTRIM(E.LX_COD_ADMINISTRADORA))  
--LEFT JOIN (Select A.LANCAMENTO_CAIXA ,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO,(VALOR_ORIGINAL_PEDIDO - isnull(DESCONTO_LOJA,0)) VALOR_TOTAL ,CONFIRMADO,CANCELADO  --#22#
  LEFT JOIN (Select A.LANCAMENTO_CAIXA ,a.terminal,UV.CODIGO_FILIAL,UV.TICKET,UV.DATA_VENDA,VALOR_ORIGINAL_PEDIDO, VALOR_PAGO, VALOR_PAGO + (VALOR_ORIGINAL_PEDIDO - ISNULL(DESCONTO_LOJA,0)) VALOR_TOTAL ,CONFIRMADO,CANCELADO --#22#
	 DESCONTO_LOJA,CANCELADO,FRETE from UNICO_VITRINE_PEDIDO UV WITH (NOLOCK)
  INNER JOIN LOJA_VENDA A WITH (NOLOCK)
	 ON  A.TICKET = UV.TICKET 
	And A.DATA_VENDA = UV.DATA_VENDA 
	And A.CODIGO_FILIAL =UV.CODIGO_FILIAL
	And A.DATA_VENDA BETWEEN CONVERT(CHAR(8),GETDATE()-30,112) AND CONVERT(CHAR(8),GETDATE(),112)) VV
	on PARCELA.LANCAMENTO_CAIXA =VV.LANCAMENTO_CAIXA and PARCELA.TERMINAL =VV.TERMINAL 
	WHERE ((PGTO.ID_EQUIPAMENTO IS NOT NULL AND  
		PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND  
			  PGTO.NUMERO_CUPOM_FISCAL IS NOT NULL )  
			OR  
			(PGTO.NUMERO_FISCAL_VENDA IS NOT NULL AND   
			ISNULL(PGTO.ID_EQUIPAMENTO , '') = '' AND   
			PGTO.NUMERO_FISCAL_VINCULADA IS NULL))
			AND isnull(VV.VALOR_ORIGINAL_PEDIDO,0) > 0  --#20#
			) A 
		  GROUP BY A.TIPO_NOTA,FILIAL, NF ,SERIE_NF,PARCELA,INFO_PGTO,VALOR --#20# #21#