select 'ALAMEDA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.5.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'BRASILIA SH' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.15.2].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'BANGU' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.6.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'BOULEVARD BRASILIA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.12.3\sqlexpress].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'RIACHUELO' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.121.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'TATUAPE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.99.2].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'PORTO VELHO' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.72.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'CNB' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.128.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'PATIO DF' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.66.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'NOVA AMERICA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.2.5\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'BOULEVARD BH' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.102.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'SALVADOR NORTE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.82.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

--select 'CENTER SH' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
--from [172.20.22.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	--LEFT join PRODUTOS RT
		--on RT.PRODUTO = LJ.PRODUTO
		--COLLATE Latin1_General_CI_AS
	--WHERE RT.PRODUTO IS NULL

--UNION

select 'PATIO BELEM' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.9.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'PLAZA CASA FORTE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.68.2].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'TACARUNA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.97.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'IGUATEMI SALVADOR' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.37.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'DIAMOND' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.27.3].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'SHOPPING SUL' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.93.3].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'MADUREIRA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.46.2].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'PRAIA DA COSTA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.73.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

--select 'CAMPO GRANDE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
--from [172.20.19.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	--LEFT join PRODUTOS RT
		--on RT.PRODUTO = LJ.PRODUTO
		--COLLATE Latin1_General_CI_AS
	--WHERE RT.PRODUTO IS NULL

--UNION

select 'BARUERI' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.62.3\sqlexpress].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'MESTRE ALVARO' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.49.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'VALE SUL' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.104.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'PONTA NEGRA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.71.2].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'PARK CAMPO GRANDE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.59.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

--select 'UBERLANDIA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
--from [172.20.11.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	--LEFT join PRODUTOS RT
		--on RT.PRODUTO = LJ.PRODUTO
		--COLLATE Latin1_General_CI_AS
	--WHERE RT.PRODUTO IS NULL

--UNION

select 'BELA VISTA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.8.3].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'ITAGUACU' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.29.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'MINAS SHOPPING' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.51.3\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'VILA VELHA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.4.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

--select 'GARDEN' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
--from [172.20.80.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	--LEFT join PRODUTOS RT
		--on RT.PRODUTO = LJ.PRODUTO
		--COLLATE Latin1_General_CI_AS
	--WHERE RT.PRODUTO IS NULL

--UNION

select 'SAO JOSE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.84.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'GONCALVES DIAS' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.32.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

--select 'SHOPPING CIDADE' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
--from [172.20.125.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	--LEFT join PRODUTOS RT
		--on RT.PRODUTO = LJ.PRODUTO
		--COLLATE Latin1_General_CI_AS
	--WHERE RT.PRODUTO IS NULL

--UNION

select 'NOVA IGUACU' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.118.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'TABOAO' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.126.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

--select 'PLAZA DF' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
--from [172.20.69.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	--LEFT join PRODUTOS RT
		--on RT.PRODUTO = LJ.PRODUTO
		--COLLATE Latin1_General_CI_AS
	--WHERE RT.PRODUTO IS NULL

--UNION

select 'NATAL SHOPPING' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.53.4\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'JK BRASILIA' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.43.2\interfacenet].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL

UNION

select 'CENTER UBERLANDIA 2' AS NOME_LOJA, LJ.PRODUTO AS PRODUTO_LOJA, RT.PRODUTO AS PRODUTO_RETAGUARDA 
from [172.20.103.3].linxpos.dbo.PRODUTOS LJ
	LEFT join PRODUTOS RT
		on RT.PRODUTO = LJ.PRODUTO
		COLLATE Latin1_General_CI_AS
	WHERE RT.PRODUTO IS NULL